### ISSUE TITLE
게시글이 중복 수집되는 문제 해결하기

### ISSUE THREAD

**Issue by crtEvent** [FlytrapHub/RSS-Reader#214]
## **☑️ 진행할 작업**
- 게시글이 중복 수집되는 문제 해결하기
<img width="1000" alt="image" src="https://github.com/FlytrapHub/RSS-Reader/assets/86359180/bae842db-df5c-4e25-8113-30370cd27481">

- 이 문제는 DB에서 게시글 guid를 Unique 키로 두는 것으로 쉽게 해결할 수 있을 것 같다. 그러나 처음에는 게시글이 중복으로 저장되지 않았는데 갑자기 중복으로 저장되는 이유가 무엇일까? 게시글 중복 저장의 미스터리를 파헤쳐보자!

**Comment by new-pow** [comment]
Unique 키로 두면 중간에 DB에러가 나서 실행 로직이 취소 되는 경우는 없나요?

**Comment by crtEvent** [comment]
> Unique 키로 두면 중간에 DB에러가 나서 실행 로직이 취소 되는 경우는 없나요?

그렇네요! 테스트해 보니 JPA의 `saveAll()` 이 한 트랜잭션으로 묶여 있어서 하나 실패하면 다 실패하는군요.

그런데! 새로 알게 된 사실 JPA의 `saveAll()`이 실제로 Bulk Insert가 아니래요. save()를 여러번 호출하는데 한 트랙잭션으로 묶여서 빠른거라고 하네요.
[saveAll() 쓰면 쿼리 하나로 나가는 거 아니었어?](https://dct-wonjung.tistory.com/entry/JPA-mysql-saveall-Bulk-Insert)
[JPA saveAll이 Bulk INSERT 되지 않았던 이유](https://imksh.com/113)

**Comment by crtEvent** [comment]
# 게시글 중복 문제 원인과 해결 방안

## 게시글 중복 문제의 원인
- **원인**: 게시글 파싱 후 Queue에 삽입된 게시글이 모두 DB에 Insert되기 전에, 다시 게시글을 파싱하여 Queue에 삽입하기 때문에 게시글이 중복으로 저장된 것이였습니다.
![게시글 수집 문제 1](https://github.com/FlytrapHub/RSS-Reader/assets/86359180/1110a9b1-0f3b-44c3-af96-ff74c3621b47)

## 추가로 발견된 문제
- **문제**: 파싱된 게시글이 Queue 사이즈보다 많을 경우, 더이상 새로운 게시글을 Queue에 삽입하지 못하는 문제
- **원인**: Queue에 삽입된 게시글을 DB에 저장하는 속도보다, 게시글을 파싱하여 Queue에 삽입하는 속도가 더 빠르다 보니. 새로 추가된 게시글이 Queue에 삽입되지 못합니다.
![게시글 수집 문제 2](https://github.com/FlytrapHub/RSS-Reader/assets/86359180/f7f32b72-854f-411c-8f07-1250252218b4)

## 해결 방안
### 게시글 수집 로직과 게시글 저장 로직을 따로 수행하지 않고 한 스케쥴에 수행하도록 한다.
- **게시글 중복 저장 문제**
  - Queue에 삽입된 게시글이 모두 DB에 저장된 후 다시 게시글을 파싱하므로 게시글이 중복될 일이 없을 것 같습니다.
- **Queue 사이즈 초과 문제**
  - 한 스케쥴에 동작하도록 하면 `게시글 수집 -> [Queue에 30개씩 저장 -> 30개씩 Bulk Insert]: 모든 게시글이 Insert될 때 까지 반복`이 한 싸이클이 될 것 같아요. Queue 사이즈를 줄일 수도 있고, 새로운 게시글을 놓칠 일 도 없을 것 같습니다.

### 2024.03.24 (일) 내용 추가
- 코드를 다시 돌려 보니 게시글 수집을 하나의 스레드가 담당하고 있네요. 예전에 여러개의 스레드로 동시에 수집하게 했었는데 Queue 만들면서 없어진 듯 합니다. 제 생각엔 게시글 수집에는 Queue가 주는 이점이 없는것 같아요. 블로그 별로 스레드를 할당하고, 블로그 별로 게시글 수집 후 바로 Bulk Insert하면 될 것 같아요. 게시글 수집 스케쥴 반복 시간도 현재 5초에서 10분 정도로 늘려도 될 것 같습니다.

**Comment by new-pow** [comment]
정성스럽게 분석해주셔서 감사해요!

queue가 주는 이점으로 DB커넥션을 줄여주고, bulk insert를 시도하셨던 것 같은데 (추가 효과가 있다면 더 설명해주세요 감자)
근데 말씀하신 시간차 때문에 중복 게시물이 발생하는 등의 문제점이 있군요!

## 해결방안 의견
- 제안해주신 방식으로는 queue를 없애고 한 스케줄에 게시글 수집과 저장 로직을 수행하도록 하는 것이 좋을 것 같아요. 생각보다 queue peek를 빨리 찍는게 문제네요 ㅜㅜ
- 다만 굳이 블로그마다 스레드를 할당하지 않아도 될 것 같아요.
    - 여러 스레드를 동시에 돌리지 않아도 한 스레드가 일해도 되지 않을까 싶어서요. 혹은 스레드 1개만 점유시켜서 그 스레드는 계속 그 일만 무한으로 실행하게 해도 되지 않나 싶었습니다. 어차피 하위 작업인 크롤링하는 작업은 비동기로 이루어지고 있는 것 같고, DB 에 넣는 작업이 여러 스레드에서 write할 경우 괜찮을지 우려됩니다.
    - 스레드를 나누면 동시성 문제가 생길일은 없는지 고려해보면 좋을 것 같습니다. (아래처럼 subscribe를 일정개수만큼 잘라 크롤링하는 경우)

## 추가 개선 방향 제안
### subscribe 를 한번에 모두 크롤링하는 문제
- 현재 크롤링 해올때 subscribe 를 모두 조회해 오는데, 이게 지금은 괜찮은데 subscribe가 많아질 때 문제가 있을 수 있을 것 같습니다.
```java
        List<SubscribeEntity> subscribes = subscribeService.findSubscribeList();
```

- 그래서 `subscribe`관련 크롤링 기록이 필요할 것 같습니다. `createdAt`, `updatedAt`은 `subscribe` 테이블에 컬럼을 추가하고. `lastCrawledAt`, `failed` 등 크롤링 관련 데이터를 별도 테이블에 추가하여 일정 개수의 subscribe씩 크롤링 하도록 하면 어떨까 싶습니다.
- `failed`같은 경우는 종종 크롤링 중 에러가 로그가 찍히는 것 같더라고요. 나중에 크롤링을 개선할 때 도움이 될까 싶어 어떤 블로그에서 에러났는지 표시하면 좋을 것 같아요.

**Comment by crtEvent** [comment]
- 크롤링 기록하자는 의견 좋아요.
  - 어떤 정보를 어떻게 저장할지 논의해보면 좋겠어요. `lastCrawledAt`이 어떻게 활용될지 아직 감이 안오네요
  - `failed`는 '어떤 블로그'의 '어떤 게시글'을 수집하다가 '어떤 에러'가 발생했는지 기록하면 좋겠어요.

- 모든 subscribe를 한번에 SELECT 하는 부분도 고민해 보겠습니다.
  - `lastCrawledAt`를 여기서 사용할 수 있을 것 같네요. 

### 지금 생각나는 로직
  ```text
  1. subscribe table에 lastCrawledAt 컬럼 추가
  2. 크롤링 스케쥴 시작
  3. 스케쥴 시작 시간을 기록한다
  4. 전체 subscribe의 개수를 SELECT 한다
  5. 'lastCrawledAt'이 스케쥴 시작 시간 이전인 subscribe 중 n개의 subscribe를 SELECT 한다.
  6. SELECT 해온 n개의 subscribe의 게시글을 파싱하여 DB에 BULK INSERT 한다. 
  7. 크롤링이 완료된 subscribe의 'lastCrawledAt'에 스케쥴 시작 기간을 기록한다.
  8. 처음 SELECT 해온 subscribe의 개수를 채울 때 까지 5~7반복...
  9. 크롤링 스케쥴 한 사이클 끝
  ```
- 스케쥴 기능 없이 크롤링 하는건 어떻게 하는지 모르겠어요. 스레드 하나 할당해서 무한 반복문 돌리는 건가요?

### 동시성 문제
- 이린 말데로 스레드 나누는건 다음 문제인것 같네요.
- 스레드를 나누지 않아도. 블로그 구독 시 크롤링을 따로 진행하게 되는데 여기서도 게시글 중복이 발생할 수 있을 것 같다는 생각이 드네요.
  - 블로그 구독시 게시글 수집 작업을 크롤링 스케줄에 추가하는 방향으로 구현해보고 싶어요

감사해요!

**Comment by new-pow** [comment]
### 데이터 저장
- `subscribe`와는 별개로 크롤링 관련 데이터를 모을만한 테이블을 생각했는데.. 지금 로직에서는 컬럼 하나로도 충분하겠네요.
- 실패할 경우에 저장할 것이 많다면 이를 로깅할만한 방법을 따로 고안해봅시다! DB에 테이블로해도 되고요!!

### 중복 제거 작업
- 현재 게시글 중복 제거는 크롤링 프로세스 중간에 DB에 저장되어 있는 값을 불러와서 Guid 를 key로 한 HashSet으로 만들어주는 것으로 중복 제거중인 것 같아요.
- 근데 위의 HashSet이 Queue로 들어가면서 List로 변환되며 중복값을 걸러주지 못한 것이죠.
- 이 로직은 리팩토링해서 크롤링 작업 밖으로 빼내는 것도 좋을 것 같습니다. (p3)

### `지금 생각나는 로직`에 대한 지금 생각나는 개선 방향
```
1. 크롤링 스케쥴 시작
2. 스케쥴 시작 시간을 기록한다
3. 'lastCrawledAt'으로 오름차순 정렬하여 N개의 subscribe를 조회해온다.
4. for 시작
  5. (서브스레드 시작)
       6. subscribe에 해당하는 게시글을 크롤링해오고, 파싱한다.
       7. (현재 여기서 중복제거 작업함. 밖으로 빼낸다면 `9번` 이전으로 빼내도 좋겠음.)
  8. (콜백)
9. DB에 BULK INSERT 한다. 
10. 크롤링이 완료된 subscribe의 'lastCrawledAt'에 스케쥴 시작 기간을 기록한다.
    11. 만약 중간에 실패했다면 'lastCrawledAt'를 업데이트하지 않고 실패 기록을 남긴다.
12. 처음 SELECT 해온 subscribe의 개수를 채울 때 까지 5~7반복...
13. 크롤링 스케쥴 한 사이클 끝
```

### 기타
- 스케줄 기능없이 크롤링하는건 말씀하신대로 스레드 하나 할당해서 무한 반복하는 것이었어요.
    - 필요한 것만 로깅되도록 고안하면 좋을 것 같아요.
    - 근데 스케줄 작업도 괜찮아서, 이 제안이 불필요하다는 생각이 든다면 굳이 하지 않아도 될 것 같아요.
