### ISSUE TITLE
프로젝트 구조 개선 아이디어 제안

### ISSUE THREAD

**Issue by crtEvent** [FlytrapHub/RSS-Reader#227]
# **☑️ 진행할 작업**
- #207 에 이어서 프로젝트 구조 개선 아이디어 제안합니다

- 이린(@new-pow)  프로젝트 리팩토링 하는 김에 제안드립니다. 제가 프론트엔드 개발하면서 백엔드 API를 하나하나 다 테스트 하게 되었습니다. 이때 발견한 추가 요구사항과 버그들을 제가 작업하게 되었는데 자잘한 요구사항 추가와 버그 해결도 꾀 힘든 경우가 종종 있었습니다. 힘들었던 부분은 요구사항을 추가하거나 버그를 고치는게 아닌, 내가 이 부분을 마음데로 변경해도 되나? 내가 추가하려는 코드를 어디에 추가해야 하지? 하는 고민들과 하나를 고쳤더니 다른 부분에서 에러가 나네? 이런 부분 때문이였습니다. 
- 멤버들 마다 이름 짖는 방식, 역할을 분리하고 책임을 할당하는 방식이 조금씩 달라서 어디에 맞춰서 작업해야 할지가 항상 고민이였습니다. 결국 대부분 제 스타일 대로 작업하게 됐지만, 다른 분들이 제 코드를 고치게 되면 저와 같은 고민을 하시게 될 것 같다는 생각이 들었습니다. 
- 이 프로젝트는 저희가 직접 쓰기 위해 만든 프로젝트고 다들 취업하시면 주말에 시간내서 작업하시게 될텐데 이런 문제들 때문에 작업이 힘들게 될 것 같습니다. 미래를 위해 규칙을 다시 정하고 변경에 유리한 구조로 개선하는데 힘을 썼으면 좋겠습니다. 더불어 지니(@jinny-l), 듀이(@jaea-kim)도 이 프로젝트에 참여하고 싶으실때 쉽게 참여할 수 있는 환경으로 만들고 싶습니다.

# Domain Model 재 설계하기
- 저희가 DDD을 차용하기 위해 RDB Model과 Domain Model을 분리했었습니다. 비즈니스 로직에 DB 종속성을 제거하여, 비즈니스 요구사항 변경에 유리한 코드를 작성하기 위함이였습니다. 저는 이 이점을 잘 못 누리고 있다고 생각합니다. 
- 저희가 RDB Model을 먼저 설계하고 RDB Model과 거의 동등하게 Domain Model을 만들어서 생긴 문제인 것 같습니다. Service 단에 비즈니스 로직과 DB에서 데이터를 불러오고 저장하기 위한 구현 로직이 섞여 있으며 Domain Model에는 로직이 거의 없습니다.
- DDD 서적들을 찾아보면 DDD를 위해서 Domain Model을 먼저 설계할 것을 요구하고 있습니다. 저희도 Domain Model을 재 설계해 보면 좋겠습니다.

- 아래는 제가 임의로 만들어본 Domain Model 설계 입니다. 아직 미완성 입니다.
![RSS Event Stoming drawio](https://github.com/FlytrapHub/RSS-Reader/assets/86359180/1cd7c076-fd6c-4add-b9e9-db85b167f3dc)
- Event Storming을 따라해 봤습니다. 필요한 Domain Model을 찾는데 도움이 된 것 같습니다.

## Model 설계하면서 비즈니스 언어 통합하기(유비쿼터스 언어 정하기) + 문서화 하기
- 같은 대상을 다르게 부르는 경우가 있어 코드를 이해하는데 어려움이 있었던 경험이 있습니다. 대표적인 예로 SharedFolder와 FolderMember 입니다. 
  - Collector와 Crawler, Blog와 RSS 그리고 Subscribe, Feed와 Post 등도 있습니다
- Domain Model을 설계하면서 용어를 통일시키고 용어를 설명하는 문서를 만들면 좋겠습니다. 새로 들어와 작업하는 팀원들이 프로젝트를 이해하는데 도움이 되고, 저희도 일관성 있게 변수명, 메서드명, 클래스명을 지을 수 있어 서로의 코드를 이해하는데 도움이 될 것 같습니다.

## Domain Model의 id를 ValueObject로 만들기
- Model 데이터를 대부분 id로 불러오고 조합하기 때문에 id를 많이 사용하게 됩니다. 문제는 두 개 이상의 Model을 조합할 때 나타납니다. 다음과 같이 List, Map의 제네릭으로 Model의 id가 Long 타입으로 들어가는데 어떤 Model의 아이디가 들어가는지 헷갈립니다.
```java
Map<Long, PostSubscribeCountOutput> countsPost
public Map<Long, List<Long>> findMembersInFolders(List<Long> invitedFolderIds)
```
- Model의 id를 ValueObject로 만들어 이 문제를 해소할 수 있을 것 같습니다.
```java
Map<PostId, PostSubscribeCountOutput> countsPost
public Map<SubscribeId, List<PostId>> findMembersInFolders(List<FolderId> invitedFolderIds)
```

# Layer 마다 섞인 로직 분리
- 현재 Presentation, Business Layer에 비즈니스 로직과 구현 로직이 섞여 있어 각 Layer의 역할이 모호하고 응집도가 떨어진다고 생각합니다.

## Presentation Controller단에 비즈니스 로직이 포함된 경우
- 저희가 Controlelr에서 Service 메서드를 조합하기로 했었는데 이 부분이 어색합니다.
- 다음은 Folder에 Member를 초대하는 API의 Controller 로직입니다.
```java
    @ResponseStatus(HttpStatus.CREATED)
    @PostMapping("/{folderId}/members")
    public ApplicationResponse<MemberSummary> inviteMember(
            @PathVariable Long folderId,
            @Login SessionMember loginMember,
            @RequestBody InviteMemberRequest request
    ) throws AuthenticationException {

        Folder verifiedFolder = folderVerifyService.getVerifiedOwnedFolder(folderId, loginMember.id());
        Member member = memberService.findById(request.inviteeId());
        sharedFolderUpdateService.invite(verifiedFolder, member.getId());
        folderUpdateService.shareFolder(verifiedFolder);

        return new ApplicationResponse<>(MemberSummary.from(member));
    }
```
- Member를 초대하면 Folder에 Member가 초대되고, Member가 초대된 Folder는 SharedFolder로 변경됩니다. 이는 비즈니스 규칙이라고 생각합니다. 따라서 위 로직은 비즈니스 로직을 담당하는 Business Layer가 가져야 한다고 생각합니다.

## Business Layer에 비즈니스 로직과 구현 로직이 섞인 경우
- 현재 Business Layer를 facade와 service로 분류하고 있습니다. Service Compnent가 다른 Domain의 Service Component를 사용하면 facade로 분류하기로 했습니다. 이 기준이 애매한 것 같습니다. Service에도 다른 Dmoain의 Repository를 사용하는 경우가 있습니다. Repository끼리 조합하여 Service가 되는 경우, Service 끼리 조합하여 Facade가 되는 경우의 기준이 모호하다고 생각합니다.
- 저는 비즈니스 로직과 구현 로직으로 Business Layer를 구분할 것을 제안합니다.
- 다음은 `MyFolderFacade`에서 내 Folder 목록을 불러오는 메서드 입니다.
```java
    public List<Folder> getMyFolders(long id) {
        List<Folder> myFolders = folderReadService.findAllByMemberId(id);

        // 내가 초대받은 폴더 목록
        List<Long> invitedFolderIds = sharedFolderReadService.findFoldersInvited(id);
        List<Folder> invitedFolders = folderReadService.findAllByIds(invitedFolderIds);

        myFolders.addAll(invitedFolders);

        return myFolders;
    }
```
- 내 Folder 목록을 불러오기 위해 '내가 생성한 Folder 목록'과 '내가 초대받은 Folder 목록'을 불러와 합치게 됩니다.
- 여기서 '내가 초대받은 Folder 목록'을 불러오는 부분을 살펴보겠습니다.
```java
// 내가 초대받은 폴더 목록
List<Long> invitedFolderIds = sharedFolderReadService.findFoldersInvited(id);
List<Folder> invitedFolders = folderReadService.findAllByIds(invitedFolderIds);
```
- '내가 초대받은 Folder 목록'을 불러오기 위해 `sharedFolderReadService`에서 내가 초대받은 Folder의 id 목록을 조회해 오고 이 id 목록으로 다시 Folder 목록을 조회해 오고 있습니다. 비즈니스 로직에서는 `내가 초대받은 Folder 목록`을 불러온다는 것이 중요한 부분이라고 생각합니다. 위 코드처럼  `내가 초대받은 Folder 목록`을 불러오는 방식은 DB와 관련된 로직이며 비즈니스 로직을 위한 구현 로직이라고 생각합니다. 이는 비즈니스 로직에서 중요하지 않다고 생각합니다.

## 제안하는 프로젝트 구조
- 따라서 제가 제안하는 프로젝트 구조는 다음과 같습니다.
<img width="263" alt="image" src="https://github.com/FlytrapHub/RSS-Reader/assets/86359180/ea541d4b-0e30-4477-bc75-9a463f47fa55">

  - Business Layer에 service와 impl 패키지를 추가합니다.
  - **service**
    - 여기서 service는 기존의 facade이며 구현 로직을 제거하고 비즈니스 로직의 흐름만 보여줍니다. service는 impl 패키지의 구현 로직을 이용해 비즈니스 로직을 표현합니다. controller는 이 service만 참조합니다.
    - 기존의 Facade 처럼 Transactional 어노테이션을 붙일 필요가 없게 만들고자 합니다. 결국 Service는 여러 Domain Model이 협력하게 되기 때문에 Transaction 범위가 커지는 것을 방지하기 위함입니다.
  - **impl**
    - 기존의 service가 impl이 됩니다. 여기서 Repository로 DB Entity를 불러와 Model로 변경하고 검증, 조합하는 구현 로직을 작성합니다. 도메인 불러오기, 검증, 조합용 이기 때문에 Service라는 이름을 붙일 필요가 없다고 생각합니다. 플래너 프로젝트에서 검증 Service를 `DomainValidator`로 명명하고 있습니다. 이처럼 `DomainValidator`, `DomainReader` 같은 식으로 명명하면 좋을 것 같습니다.

- 리팩토링 작업 하면서 테스트로 같이 변경하면 좋을 것 같습니다.

**Comment by new-pow** [comment]
## 추가 제안하는 것
### Repository
- Repository 역할도 분리하자
  - entity를 Repository layer에서만 사용

### service
- aggregate 도입
  - 데이터가 변경되는 경우 aggregate 로직을 거치도록 해보자

**Comment by new-pow** [comment]
👏 에이프 멋져요
